routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');




Route::resource('users', 'UserController');

Route::resource('clothes', 'ClothesController');

Route::resource('orders', 'OrderController');

Route::resource('payments', 'PaymentController');

Route::resource('roles', 'RoleController');

Route::resource('orderclothes', 'OrderClothesController');

Route::resource('orderpayments', 'OrderPaymentController');

app/Models/Order.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Order
 * @package App\Models
 * @version December 26, 2020, 9:53 am UTC
 *
 * @property \App\Models\User $customer
 * @property \Illuminate\Database\Eloquent\Collection $clothes
 * @property \Illuminate\Database\Eloquent\Collection $payments
 * @property string $status
 * @property integer $customer_id
 */
class Order extends Model
{
    use SoftDeletes;

    public $table = 'orders';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'status',
        'customer_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'status' => 'string',
        'customer_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'status' => 'required|string|max:255',
        'customer_id' => 'required',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function customer()
    {
        return $this->belongsTo(\App\Models\User::class, 'customer_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function clothes()
    {
        return $this->belongsToMany(\App\Models\Clothes::class, 'clothes_orders')
                                ->withPivot('quantity');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function payments()
    {
        return $this->hasMany(\App\Models\Payment::class, 'order_id');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateOrderRequest;
use App\Http\Requests\UpdateOrderRequest;
use App\Repositories\OrderRepository;
use App\Repositories\UserRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class OrderController extends AppBaseController
{
    /** @var  OrderRepository */
    private $orderRepository;
    private $userRepository;

    public function __construct(OrderRepository $orderRepo, UserRepository $userRepo)
    {
        $this->orderRepository = $orderRepo;
        $this->userRepository = $userRepo;
    }

    /**
     * Display a listing of the Order.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $orders = $this->orderRepository->all();
        $users = $this->userRepository->all();

        $users = $this->getdropdownData($users);

        return view('orders.index')
            ->with('orders', $orders)
            ->with('clients',$users);
    }

    /**
     * Show the form for creating a new Order.
     *
     * @return Response
     */
    public function create()
    {
        $order = $this->orderRepository->model();
        $order = new $order;

        $users = $this->userRepository->all();

        $users = $this->getdropdownData($users);

        return view('orders.create')
            ->with('order', $order)
            ->with('clients', $users);
        
    }

    /**
     * Store a newly created Order in storage.
     *
     * @param CreateOrderRequest $request
     *
     * @return Response
     */
    public function store(CreateOrderRequest $request)
    {
        $input = $request->all();

        $order = $this->orderRepository->create($input);

        Flash::success('Order saved successfully.');

        return redirect(route('orders.index'));
    }

    /**
     * Display the specified Order.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $order = $this->orderRepository->find($id);

        $clothes = $order->clothes;

        if (empty($order)) {
            Flash::error('Order not found');

            return redirect(route('orders.index'));
        }

        //Cache::put('order_id', $id);
        session(['order_id' => $id]);

        $order_price = 0;

        foreach ($order->clothes as $c)
        {
            $quantity = $c->pivot->quantity;
            $price = $c->price;

            $order_price += $quantity * $price;            
        }

        $order_paid = 0;

        foreach ($order->payments as $p)
        {
            $order_paid += $p->amount;           
        }
        
        return view('orders.show')
            ->with('clothes', $clothes)
            ->with('order', $order)
            ->with('order_price', $order_price)
            ->with('order_paid', $order_paid);
    }

    /**
     * Show the form for editing the specified Order.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $order = $this->orderRepository->find($id);

        $users = $this->userRepository->all();

        $users = $this->getdropdownData($users);

        if (empty($order)) {
            Flash::error('Order not found');

            return redirect(route('orders.index'));
        }

        return view('orders.edit')->with('order', $order)->with('clients', $users);
    }

    /**
     * Update the specified Order in storage.
     *
     * @param int $id
     * @param UpdateOrderRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOrderRequest $request)
    {
        $order = $this->orderRepository->find($id);

        if (empty($order)) {
            Flash::error('Order not found');

            return redirect(route('orders.index'));
        }

        $order = $this->orderRepository->update($request->all(), $id);

        Flash::success('Order updated successfully.');

        return redirect(route('orders.index'));
    }

    /**
     * Remove the specified Order from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $order = $this->orderRepository->find($id);

        if (empty($order)) {
            Flash::error('Order not found');

            return redirect(route('orders.index'));
        }

        $this->orderRepository->delete($id);

        Flash::success('Order deleted successfully.');

        return redirect(route('orders.index'));
    }
}

resources/views/orders/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('orders.index') !!}">Order</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Order</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'orders.store']) !!}

                                   @include('orders.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/orders/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('orders.index') !!}">Order</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Order</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($order, ['route' => ['orders.update', $order->id], 'method' => 'patch']) !!}

                              @include('orders.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/orders/fields.blade.php
<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::select('status', ['Washing' => 'Washing', 'Drying' => 'Drying', 'Delivery' => 'Delivery', 'Complete' => 'Complete'], 
        $order->status, ['placeholder' => 'Pick a Status...','class' => 'form-control'])!!}
</div>

<!-- Customer Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('customer_id', 'Customer:') !!}    
    {!! Form::select('customer_id', $clients, $order->customer_id, ['placeholder' => 'Pick a client type...','class' => 'form-control'])!!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('orders.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Orders</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Orders
                             <a class="pull-right" href="{{ route('orders.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('orders.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/orders/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('orders.index') }}">Order</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('orders.index') }}" class="btn btn-dark pull-right">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('orders.show_fields')
                             </div>
                         </div>

                         <div class="card">
                             <div class="card-header">
                                 <i class="fa fa-align-justify"></i>
                                 <strong>Submitted Clothes</strong> 
                                 <a class="pull-right" href="{{ route('orderclothes.create',[$order->id]) }}"><i class="fa fa-plus-square fa-lg"></i></a>                                 
                             </div>
                             <div class="card-body">
                                <div class="table-responsive-sm">
                                    <table class="table table-striped" id="clothes-table">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Price (KSH)</th>
                                                <th>Quantity</th>
                                                <th>Total ({{$order_price}} KSH)</th>
                                                <th colspan="3">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($clothes as $c)
                                            <tr>                                                
                                                <td>{{ $c->name }}</td>
                                                <td>{{ $c->price }}</td>
                                                <td>{{ $c->pivot->quantity }}</td>
                                                <td>{{ $c->price * $c->pivot->quantity}} </td>
                                                <td>
                                                    {!! Form::open(['route' => ['orderclothes.destroy', $c->id], 'method' => 'delete']) !!}
                                                    {!! Form::hidden('order_id',$order->id) !!}
                                                    <div class='btn-group'>                                                        
                                                        <a href="{{ route('orderclothes.edit', [$c ?? ''->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                                                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                                    </div>
                                                    {!! Form::close() !!}
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                             </div>
                         </div>
                         <div class="card">
                             <div class="card-header">
                                 <i class="fa fa-align-justify"></i>
                                 <strong>Payments Made</strong>
                                 <a class="pull-right" href="{{ route('orderpayments.create',[$order->id]) }}"><i class="fa fa-plus-square fa-lg"></i></a>                                  
                             </div>
                             <div class="card-body">
                                <div class="table-responsive-sm">
                                    <table class="table table-striped" id="payments-table">
                                        <thead>
                                            <tr>
                                                <th>Date</th>
                                                <th>Amount ({{$order_paid}} KSH)</th>                                                                                                
                                                <th colspan="3">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($order->payments as $payment)
                                            <tr>
                                                <td>{{ $payment->date }}</td> 
                                                <td>{{ $payment->amount }}</td>                                               
                                                <td>
                                                    {!! Form::open(['route' => ['orderpayments.destroy', $payment->id], 'method' => 'delete']) !!}
                                                    <div class='btn-group'>                                                        
                                                        <a href="{{ route('orderpayments.edit', [$payment->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                                                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                                    </div>
                                                    {!! Form::close() !!}
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/orders/show_fields.blade.php
<!-- Status Field -->
<div class="form-group">
    <strong>{!! Form::label('status', 'Status:') !!}</strong>
    {{ $order->status }}
</div>

<!-- Customer Id Field -->
<div class="form-group">
    <strong>{!! Form::label('customer_id', 'Customer Name:') !!}</strong>
    {{ $order->customer->name }}
</div>

<div class="form-group">
    <strong>{!! Form::label('balance', 'Amount Due:') !!}</strong>
    {{ $order_price - $order_paid }} KSH.
</div>

resources/views/orders/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="orders-table">
        <thead>
            <tr>
                <th>Order Number </th>
                <th>Customer Name</th>
                <th>Status</th>                
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($orders as $order)
            <tr>
                <td>{{ $order->id }}</td>
                <td>{{ $order->customer->name }}</td>
                <td>{{ $order->status }}</td>                
                <td>
                    {!! Form::open(['route' => ['orders.destroy', $order->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('orders.show', [$order->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('orders.edit', [$order->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>